require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - dictum.gemspec
    - lib/tasks/dictum.rake
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/FilePath:
  Exclude:
    - spec/xtract_sdk/version_spec.rb
